# Generated by Django 3.0.5 on 2024-11-21 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
